# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.define "centos-large", autostart:false do |lg|

    lg.vm.box = "chef/centos-6.5"

    lg.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus = 4
    end

    lg.vm.provider "parallels" do |pl|
      pl.memory = 2048
      pl.cpus = 4
    end

  end

  config.vm.define "centos-medium", autostart:false do |med|

    med.vm.box = "chef/centos-6.5"

    med.vm.provider "virtualbox" do |vb|
     vb.memory = 1024
     vb.cpus = 2
    end

    med.vm.provider "parallels" do |pl|
      pl.memory = 1024
      pl.cpus = 2
    end

  end

  config.vm.define "centos-small", autostart:false do |sm|

    sm.vm.box = "chef/centos-6.5"

    sm.vm.provider "virtualbox" do |vb|
     vb.memory = 512
     vb.cpus = 1
    end

    sm.vm.provider "parallels" do |pl|
      pl.memory = 512
      pl.cpus = 1
    end

  end

end
